### ISSUE TITLE
Doesn't work on Windows; cannot load such file pty

### ISSUE THREAD

**Issue by Phrogz** [johnae/sambal#30]
```
C:\www\dashstats\logs>gem install sambal
Fetching: sambal-0.1.7.gem (100%)
Successfully installed sambal-0.1.7
1 gem installed

C:\www\dashstats\logs>irb
irb(main):001:0> require 'sambal'
LoadError: cannot load such file -- pty
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/sambal-0.1.7/lib/sambal/client.rb:4:in `<top (required)>'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/sambal-0.1.7/lib/sambal.rb:5:in `<top (required)>'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby/bin/irb:11:in `<main>'
irb(main):002:0> RUBY_VERSION
=> "2.2.6"
```

**Comment by johnae** [comment]
Yeah I never tested it on Windows nor did I have a need for running it on that platform. You're welcome to look into it, I'm not going to have time to do the work myself.

**Comment by Phrogz** [comment]
Your repository, your rules. However, I'm surprised that you would close a valid issue just because you personally don't have time or interest to fix it. IMHO, the issue represents a valid bug against this project.

**Comment by johnae** [comment]
I possibly closed this too early, however, I'm not aware of a samba suite that's available on Windows - samba is very Unix centered. Since this drives the smbclient of samba (using a Pty which is also a very Unix centered thing) I don't see any way of supporting Windows other than a complete rethink and rewrite which is probably a completely new gem.

Obviously SMB originates in Windows but samba, which this gem is based on, is very much a Unix implementation.

Do you see an easier way forward than I do perhaps?

**Comment by Phrogz** [comment]
Nope! The ideal way forward, IMHO, is to have a completely different back-end of code for Windows that uses the same interface you've already defined.
